import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // HiddenPro — Forest / cream brand tokens; dark surfaces retained for admin.
        primary: "#176b57",
        "primary-dim": "#124c40",
        "primary-fixed": "#176b57",
        "primary-fixed-dim": "#124c40",
        "on-primary": "#ffffff",
        "on-primary-container": "#124c40",
        "on-primary-fixed-variant": "#124c40",
        secondary: "#647f57",
        "secondary-fixed": "#e2edda",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#173e31",
        "on-secondary-fixed-variant": "#466438",
        "on-secondary-container": "#edf3e7",
        tertiary: "#b5ffc2",
        "tertiary-fixed": "#3fff8b",
        "tertiary-fixed-dim": "#24f07e",
        "tertiary-container": "#3fff8b",
        "on-tertiary": "#006731",
        "on-tertiary-container": "#005d2c",
        background: "#0f0d13",
        "on-background": "#f8f1fb",
        surface: "#0f0d13",
        "surface-variant": "#27242d",
        "surface-tint": "#176b57",
        "surface-container": "#1b1820",
        "surface-container-low": "#151219",
        "surface-container-high": "#211e26",
        "surface-container-highest": "#27242d",
        "surface-container-lowest": "#000000",
        "on-surface": "#f8f1fb",
        "on-surface-variant": "#aea9b2",
        "inverse-surface": "#fef7ff",
        "inverse-on-surface": "#57545b",
        "inverse-primary": "#176b57",
        outline: "#78747c",
        "outline-variant": "#4a464f",
        error: "#ff6e84",
        "error-container": "#a70138",
        "error-dim": "#d73357",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        "secondary-container": "#173e31",
      },
      fontFamily: {
        sans: ["Manrope", "Apple SD Gothic Neo", "Malgun Gothic", "sans-serif"],
        headline: ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        body: ["Manrope", "Apple SD Gothic Neo", "Malgun Gothic", "sans-serif"],
        label: ["Manrope", "Apple SD Gothic Neo", "Malgun Gothic", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
