export const PHILIPPINES_REGIONS: Record<string, string[]> = {
  전체: ["전체"],
  "Metro Manila (NCR)": [
    "Caloocan City",
    "Las Piñas City",
    "Makati City",
    "Malabon City",
    "Mandaluyong City",
    "Manila City",
    "Marikina City",
    "Muntinlupa City",
    "Navotas City",
    "Parañaque City",
    "Pasay City",
    "Pasig City",
    "Pateros",
    "Quezon City",
    "San Juan City",
    "Taguig City",
    "Valenzuela City",
  ],
  "CAR (Cordillera)": [
    "Abra",
    "Apayao",
    "Benguet",
    "Baguio City",
    "Ifugao",
    "Kalinga",
    "Mountain Province",
  ],
  "Ilocos Region (Region I)": [
    "Ilocos Norte",
    "Ilocos Sur",
    "La Union",
    "Pangasinan",
    "Laoag City",
    "Vigan City",
    "San Fernando City",
    "Dagupan City",
    "Urdaneta City",
    "Alaminos City",
  ],
  "Cagayan Valley (Region II)": [
    "Batanes",
    "Cagayan",
    "Isabela",
    "Nueva Vizcaya",
    "Quirino",
    "Tuguegarao City",
    "Santiago City",
    "Cauayan City",
    "Ilagan City",
  ],
  "Central Luzon (Region III)": [
    "Aurora",
    "Bataan",
    "Bulacan",
    "Nueva Ecija",
    "Pampanga",
    "Tarlac",
    "Zambales",
    "Angeles City",
    "Balanga City",
    "Cabanatuan City",
    "Malolos City",
    "Meycauayan City",
    "Olongapo City",
    "San Fernando City",
    "San Jose City",
    "Tarlac City",
  ],
  "CALABARZON (Region IV-A)": [
    "Batangas",
    "Cavite",
    "Laguna",
    "Quezon",
    "Rizal",
    "Antipolo City",
    "Bacoor City",
    "Batangas City",
    "Biñan City",
    "Cabuyao City",
    "Calamba City",
    "Dasmariñas City",
    "General Trias City",
    "Imus City",
    "Lipa City",
    "Lucena City",
    "San Pablo City",
    "San Pedro City",
    "Santa Rosa City",
    "Tanauan City",
    "Trece Martires City",
  ],
  "MIMAROPA (Region IV-B)": [
    "Marinduque",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Romblon",
    "Calapan City",
    "Puerto Princesa City",
  ],
  "Bicol Region (Region V)": [
    "Albay",
    "Camarines Norte",
    "Camarines Sur",
    "Catanduanes",
    "Masbate",
    "Sorsogon",
    "Legazpi City",
    "Naga City",
    "Iriga City",
    "Ligao City",
    "Tabaco City",
    "Masbate City",
    "Sorsogon City",
  ],
  "Western Visayas (Region VI)": [
    "Aklan",
    "Antique",
    "Capiz",
    "Guimaras",
    "Iloilo",
    "Negros Occidental",
    "Bacolod City",
    "Iloilo City",
    "Kabankalan City",
    "Roxas City",
    "Sagay City",
    "San Carlos City",
    "Silay City",
    "Talisay City",
  ],
  "Central Visayas (Region VII)": [
    "Bohol",
    "Cebu",
    "Negros Oriental",
    "Siquijor",
    "Bogo City",
    "Carcar City",
    "Cebu City",
    "Danao City",
    "Lapu-Lapu City",
    "Mandaue City",
    "Naga City",
    "Talisay City",
    "Toledo City",
    "Dumaguete City",
    "Tagbilaran City",
  ],
  "Eastern Visayas (Region VIII)": [
    "Biliran",
    "Eastern Samar",
    "Leyte",
    "Northern Samar",
    "Samar",
    "Southern Leyte",
    "Tacloban City",
    "Ormoc City",
    "Baybay City",
  ],
  "Zamboanga Peninsula (Region IX)": [
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
    "Zamboanga City",
    "Dipolog City",
    "Dapitan City",
    "Pagadian City",
  ],
  "Northern Mindanao (Region X)": [
    "Bukidnon",
    "Camiguin",
    "Lanao del Norte",
    "Misamis Occidental",
    "Misamis Oriental",
    "Cagayan de Oro City",
    "Iligan City",
    "Malaybalay City",
    "Ozamiz City",
    "Oroquieta City",
    "Valencia City",
    "Gingoog City",
    "El Salvador City",
  ],
  "Davao Region (Region XI)": [
    "Davao de Oro",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Davao City",
    "Digos City",
    "Island Garden City of Samal",
    "Panabo City",
    "Tagum City",
    "Mati City",
  ],
  "SOCCSKSARGEN (Region XII)": [
    "Cotabato",
    "Sarangani",
    "South Cotabato",
    "Sultan Kudarat",
    "General Santos City",
    "Cotabato City",
    "Kidapawan City",
    "Koronadal City",
    "Tacurong City",
  ],
  "Caraga (Region XIII)": [
    "Agusan del Norte",
    "Agusan del Sur",
    "Dinagat Islands",
    "Surigao del Norte",
    "Surigao del Sur",
    "Butuan City",
    "Surigao City",
    "Bislig City",
    "Bayugan City",
    "Cabadbaran City",
    "Tandag City",
  ],
  "BARMM (Bangsamoro)": [
    "Basilan",
    "Lanao del Sur",
    "Maguindanao del Norte",
    "Maguindanao del Sur",
    "Sulu",
    "Tawi-Tawi",
    "Cotabato City",
    "Lamitan City",
    "Marawi City",
  ],
  "Negros Island Region (NIR)": [
    "Negros Occidental",
    "Negros Oriental",
    "Siquijor",
    "Bacolod City",
    "Dumaguete City",
    "Kabankalan City",
    "Sagay City",
    "San Carlos City",
    "Silay City",
    "Talisay City",
    "Bais City",
    "Bayawan City",
    "Canlaon City",
  ],
};

// 프로필 이미지 쿨다운 설정 (단위: 일)
// 추후 관리자 DB config 테이블로 이관 예정
export const PROFILE_IMAGE_COOLDOWN_DAYS = 7;
export const PROFILE_IMAGE_MAX_SIZE_BYTES = 5 * 1024 * 1024; // 5MB

// 활동명 쿨다운 설정 (단위: 일)
export const NICKNAME_COOLDOWN_DAYS = 30;
